/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPlanosAcaoRouteImport } from './routes/_authenticated/planos-acao'
import { Route as AuthenticatedNaoConformidadesRouteImport } from './routes/_authenticated/nao-conformidades'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNaoConformidadesIdRouteImport } from './routes/_authenticated/nao-conformidades.$id'
import { Route as AuthenticatedChecklistExecutionIdRouteImport } from './routes/_authenticated/checklist.$executionId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminChecklistsRouteImport } from './routes/_authenticated/admin.checklists'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosAcaoRoute = AuthenticatedPlanosAcaoRouteImport.update({
  id: '/planos-acao',
  path: '/planos-acao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNaoConformidadesRoute =
  AuthenticatedNaoConformidadesRouteImport.update({
    id: '/nao-conformidades',
    path: '/nao-conformidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNaoConformidadesIdRoute =
  AuthenticatedNaoConformidadesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedNaoConformidadesRoute,
  } as any)
const AuthenticatedChecklistExecutionIdRoute =
  AuthenticatedChecklistExecutionIdRouteImport.update({
    id: '/checklist/$executionId',
    path: '/checklist/$executionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminChecklistsRoute =
  AuthenticatedAdminChecklistsRouteImport.update({
    id: '/admin/checklists',
    path: '/admin/checklists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ia': typeof AuthenticatedIaRoute
  '/nao-conformidades': typeof AuthenticatedNaoConformidadesRouteWithChildren
  '/planos-acao': typeof AuthenticatedPlanosAcaoRoute
  '/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/checklist/$executionId': typeof AuthenticatedChecklistExecutionIdRoute
  '/nao-conformidades/$id': typeof AuthenticatedNaoConformidadesIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ia': typeof AuthenticatedIaRoute
  '/nao-conformidades': typeof AuthenticatedNaoConformidadesRouteWithChildren
  '/planos-acao': typeof AuthenticatedPlanosAcaoRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/checklist/$executionId': typeof AuthenticatedChecklistExecutionIdRoute
  '/nao-conformidades/$id': typeof AuthenticatedNaoConformidadesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/nao-conformidades': typeof AuthenticatedNaoConformidadesRouteWithChildren
  '/_authenticated/planos-acao': typeof AuthenticatedPlanosAcaoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/checklist/$executionId': typeof AuthenticatedChecklistExecutionIdRoute
  '/_authenticated/nao-conformidades/$id': typeof AuthenticatedNaoConformidadesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ia'
    | '/nao-conformidades'
    | '/planos-acao'
    | '/admin/checklists'
    | '/admin/usuarios'
    | '/checklist/$executionId'
    | '/nao-conformidades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/ia'
    | '/nao-conformidades'
    | '/planos-acao'
    | '/'
    | '/admin/checklists'
    | '/admin/usuarios'
    | '/checklist/$executionId'
    | '/nao-conformidades/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/ia'
    | '/_authenticated/nao-conformidades'
    | '/_authenticated/planos-acao'
    | '/_authenticated/'
    | '/_authenticated/admin/checklists'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/checklist/$executionId'
    | '/_authenticated/nao-conformidades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-acao': {
      id: '/_authenticated/planos-acao'
      path: '/planos-acao'
      fullPath: '/planos-acao'
      preLoaderRoute: typeof AuthenticatedPlanosAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nao-conformidades': {
      id: '/_authenticated/nao-conformidades'
      path: '/nao-conformidades'
      fullPath: '/nao-conformidades'
      preLoaderRoute: typeof AuthenticatedNaoConformidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nao-conformidades/$id': {
      id: '/_authenticated/nao-conformidades/$id'
      path: '/$id'
      fullPath: '/nao-conformidades/$id'
      preLoaderRoute: typeof AuthenticatedNaoConformidadesIdRouteImport
      parentRoute: typeof AuthenticatedNaoConformidadesRoute
    }
    '/_authenticated/checklist/$executionId': {
      id: '/_authenticated/checklist/$executionId'
      path: '/checklist/$executionId'
      fullPath: '/checklist/$executionId'
      preLoaderRoute: typeof AuthenticatedChecklistExecutionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/checklists': {
      id: '/_authenticated/admin/checklists'
      path: '/admin/checklists'
      fullPath: '/admin/checklists'
      preLoaderRoute: typeof AuthenticatedAdminChecklistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedNaoConformidadesRouteChildren {
  AuthenticatedNaoConformidadesIdRoute: typeof AuthenticatedNaoConformidadesIdRoute
}

const AuthenticatedNaoConformidadesRouteChildren: AuthenticatedNaoConformidadesRouteChildren =
  {
    AuthenticatedNaoConformidadesIdRoute: AuthenticatedNaoConformidadesIdRoute,
  }

const AuthenticatedNaoConformidadesRouteWithChildren =
  AuthenticatedNaoConformidadesRoute._addFileChildren(
    AuthenticatedNaoConformidadesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedNaoConformidadesRoute: typeof AuthenticatedNaoConformidadesRouteWithChildren
  AuthenticatedPlanosAcaoRoute: typeof AuthenticatedPlanosAcaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminChecklistsRoute: typeof AuthenticatedAdminChecklistsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedChecklistExecutionIdRoute: typeof AuthenticatedChecklistExecutionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedNaoConformidadesRoute:
    AuthenticatedNaoConformidadesRouteWithChildren,
  AuthenticatedPlanosAcaoRoute: AuthenticatedPlanosAcaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminChecklistsRoute: AuthenticatedAdminChecklistsRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedChecklistExecutionIdRoute:
    AuthenticatedChecklistExecutionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
