/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as AuthenticatedApresentacaoRouteImport } from './routes/_authenticated/apresentacao'
import { Route as AuthenticatedEstruturaRouteImport } from './routes/_authenticated/estrutura'
import { Route as AuthenticatedMetodoRouteImport } from './routes/_authenticated/metodo'
import { Route as AuthenticatedMeuTrabalhoRouteImport } from './routes/_authenticated/meu-trabalho'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedPlanosDeAcaoRouteImport } from './routes/_authenticated/planos-de-acao'
import { Route as AuthenticatedRotinasRouteImport } from './routes/_authenticated/rotinas'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApresentacaoRoute =
  AuthenticatedApresentacaoRouteImport.update({
    id: '/apresentacao',
    path: '/apresentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstruturaRoute = AuthenticatedEstruturaRouteImport.update({
  id: '/estrutura',
  path: '/estrutura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetodoRoute = AuthenticatedMetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuTrabalhoRoute =
  AuthenticatedMeuTrabalhoRouteImport.update({
    id: '/meu-trabalho',
    path: '/meu-trabalho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosDeAcaoRoute =
  AuthenticatedPlanosDeAcaoRouteImport.update({
    id: '/planos-de-acao',
    path: '/planos-de-acao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotinasRoute = AuthenticatedRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/apresentacao': typeof AuthenticatedApresentacaoRoute
  '/estrutura': typeof AuthenticatedEstruturaRoute
  '/metodo': typeof AuthenticatedMetodoRoute
  '/meu-trabalho': typeof AuthenticatedMeuTrabalhoRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/planos-de-acao': typeof AuthenticatedPlanosDeAcaoRoute
  '/rotinas': typeof AuthenticatedRotinasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/apresentacao': typeof AuthenticatedApresentacaoRoute
  '/estrutura': typeof AuthenticatedEstruturaRoute
  '/metodo': typeof AuthenticatedMetodoRoute
  '/meu-trabalho': typeof AuthenticatedMeuTrabalhoRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/planos-de-acao': typeof AuthenticatedPlanosDeAcaoRoute
  '/rotinas': typeof AuthenticatedRotinasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/apresentacao': typeof AuthenticatedApresentacaoRoute
  '/_authenticated/estrutura': typeof AuthenticatedEstruturaRoute
  '/_authenticated/metodo': typeof AuthenticatedMetodoRoute
  '/_authenticated/meu-trabalho': typeof AuthenticatedMeuTrabalhoRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/planos-de-acao': typeof AuthenticatedPlanosDeAcaoRoute
  '/_authenticated/rotinas': typeof AuthenticatedRotinasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acessos'
    | '/apresentacao'
    | '/estrutura'
    | '/metodo'
    | '/meu-trabalho'
    | '/planejamento'
    | '/planos-de-acao'
    | '/rotinas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/acessos'
    | '/apresentacao'
    | '/estrutura'
    | '/metodo'
    | '/meu-trabalho'
    | '/planejamento'
    | '/planos-de-acao'
    | '/rotinas'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/acessos'
    | '/_authenticated/apresentacao'
    | '/_authenticated/estrutura'
    | '/_authenticated/metodo'
    | '/_authenticated/meu-trabalho'
    | '/_authenticated/planejamento'
    | '/_authenticated/planos-de-acao'
    | '/_authenticated/rotinas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apresentacao': {
      id: '/_authenticated/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof AuthenticatedApresentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrutura': {
      id: '/_authenticated/estrutura'
      path: '/estrutura'
      fullPath: '/estrutura'
      preLoaderRoute: typeof AuthenticatedEstruturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metodo': {
      id: '/_authenticated/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof AuthenticatedMetodoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-trabalho': {
      id: '/_authenticated/meu-trabalho'
      path: '/meu-trabalho'
      fullPath: '/meu-trabalho'
      preLoaderRoute: typeof AuthenticatedMeuTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-de-acao': {
      id: '/_authenticated/planos-de-acao'
      path: '/planos-de-acao'
      fullPath: '/planos-de-acao'
      preLoaderRoute: typeof AuthenticatedPlanosDeAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotinas': {
      id: '/_authenticated/rotinas'
      path: '/rotinas'
      fullPath: '/rotinas'
      preLoaderRoute: typeof AuthenticatedRotinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedApresentacaoRoute: typeof AuthenticatedApresentacaoRoute
  AuthenticatedEstruturaRoute: typeof AuthenticatedEstruturaRoute
  AuthenticatedMetodoRoute: typeof AuthenticatedMetodoRoute
  AuthenticatedMeuTrabalhoRoute: typeof AuthenticatedMeuTrabalhoRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedPlanosDeAcaoRoute: typeof AuthenticatedPlanosDeAcaoRoute
  AuthenticatedRotinasRoute: typeof AuthenticatedRotinasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedApresentacaoRoute: AuthenticatedApresentacaoRoute,
  AuthenticatedEstruturaRoute: AuthenticatedEstruturaRoute,
  AuthenticatedMetodoRoute: AuthenticatedMetodoRoute,
  AuthenticatedMeuTrabalhoRoute: AuthenticatedMeuTrabalhoRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedPlanosDeAcaoRoute: AuthenticatedPlanosDeAcaoRoute,
  AuthenticatedRotinasRoute: AuthenticatedRotinasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
